### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by kenjones-cisco** [chiefy/vaulted#12]
A travis build definition: (once the most upcoming code base updates happen)

``` yaml
sudo: required

services:
  - docker

# make sure all images are available locally and then start them up in the background
before_install:
  - docker pull kenjones/authstore-consul
  - docker pull kenjones/authstore-vault
  - docker pull kenjones/nodejs-mocha
  - docker-compose --x-networking -f docker-compose-test.yml up -d

# the sleep statement should give enough time for the containers to start up
script:
  - sleep 30
  - docker run -it --rm -v `pwd`:/app --net=vaulted kenjones/nodejs-mocha sh -c 'npm install --quiet && npm run coverage'

# token can be added after registering with CodeClimate
addons:
  code_climate:
    repo_token: XXXX

# clean up the running support processes and then report code coverage to CodeClimate
after_script:
  - docker-compose -f docker-compose-test.yml stop
  - docker-compose -f docker-compose-test.yml rm -f
  - codeclimate-test-reporter < lcov.info
```

Requires setting up free account at https://travis-ci.org/ and for code coverage and static analysis https://codeclimate.com/
